# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxfy < Formula
  desc "CLI HTTPS proxy for mobile debugging. A lightweight alternative to Charles Proxy and Proxyman."
  homepage "https://github.com/ferdikt/proxfy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FerdiKT/proxfy/releases/download/v0.1.0/proxfy_darwin_amd64.tar.gz"
      sha256 "19a2e4d8cb801b4dc1d9077b639d05b560b04379dd812ed5806d9769f9cd30df"

      define_method(:install) do
        bin.install "proxfy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FerdiKT/proxfy/releases/download/v0.1.0/proxfy_darwin_arm64.tar.gz"
      sha256 "909cddcd9aab4547d0ae8d468cdd0c610459d03b887426500df9e16f8d5fc2bb"

      define_method(:install) do
        bin.install "proxfy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerdiKT/proxfy/releases/download/v0.1.0/proxfy_linux_amd64.tar.gz"
      sha256 "5a19b9acc38e76d080d6be7657b47a73cc4cbd1226134a18ea01c1c53f667e2f"
      define_method(:install) do
        bin.install "proxfy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FerdiKT/proxfy/releases/download/v0.1.0/proxfy_linux_arm64.tar.gz"
      sha256 "30bb7dce171fafab20157a9d4fe180e023595ea8d0033940ee27779c1e6979e1"
      define_method(:install) do
        bin.install "proxfy"
      end
    end
  end

  test do
    assert_match "proxfy", shell_output("#{bin}/proxfy version")
  end
end
